
package ec.edu.ups.exm.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-08-03T22:41:04.918-05:00
 * Generated source version: 2.7.11
 * 
 */
public final class ServicesSOAP_ServicesSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.exm.ups.edu.ec/", "ServicesSOAPService");

    private ServicesSOAP_ServicesSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServicesSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServicesSOAPService ss = new ServicesSOAPService(wsdlURL, SERVICE_NAME);
        ServicesSOAP port = ss.getServicesSOAPPort();  
        
        {
        System.out.println("Invoking crearProducto...");
        ec.edu.ups.exm.services.Producto _crearProducto_arg0 = null;
        java.lang.String _crearProducto__return = port.crearProducto(_crearProducto_arg0);
        System.out.println("crearProducto.result=" + _crearProducto__return);


        }
        {
        System.out.println("Invoking miCarrito...");
        java.lang.String _miCarrito_arg0 = "";
        java.util.List<ec.edu.ups.exm.services.Carro> _miCarrito__return = port.miCarrito(_miCarrito_arg0);
        System.out.println("miCarrito.result=" + _miCarrito__return);


        }
        {
        System.out.println("Invoking listaProductos...");
        java.util.List<ec.edu.ups.exm.services.Producto> _listaProductos__return = port.listaProductos();
        System.out.println("listaProductos.result=" + _listaProductos__return);


        }
        {
        System.out.println("Invoking addCarrito...");
        ec.edu.ups.exm.services.Carro _addCarrito_arg0 = null;
        java.lang.String _addCarrito__return = port.addCarrito(_addCarrito_arg0);
        System.out.println("addCarrito.result=" + _addCarrito__return);


        }
        {
        System.out.println("Invoking llenarCarrito...");
        java.util.List<ec.edu.ups.exm.services.Carro> _llenarCarrito_arg0 = null;
        java.lang.String _llenarCarrito__return = port.llenarCarrito(_llenarCarrito_arg0);
        System.out.println("llenarCarrito.result=" + _llenarCarrito__return);


        }

        System.exit(0);
    }

}
